server:
  port: 9100
#  contextPath: /test


#### SPRING SECURITY JWT ####

security:
  oauth2:
    resource:
      filter-order: 3
  signing-key: JouR3er6jIkFPo
  security-realm: Tennis Corpo Engine Realm
  jwt:
    client-id: tenniscorpoclientid
    client-secret: ABi8u34kPoDo
    grant-type-password: password
    grant-type-refresh-token: refresh_token
    scope-read: read
    scope-write: write
    resource-ids: tenniscorporesourceid
  allow-origin: http://localhost:4200


#### GOOGLE OAUTH2 #####

#security:
#  oauth2:
#    client:
#      clientId: 717361552560-gobijh408olcag1nitv4dk8mk2o1ul9k.apps.googleusercontent.com
#      clientSecret: MLdQkmjHO5Cfz6pcs340vC4H
#      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
#      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
#      clientAuthenticationScheme: form
#      scope:
#        - openid
#        - email
#        - profile
#    resource:
#      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
#      preferTokenInfo: true

#### DATASOURCE ####

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tennisCorpo
    username: fca
    password: fca
    driver-class: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/tennisCorpo
#    username: fca
#    password: fca
#    driver-class: org.postgresql.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG94Dialect
#    show-sql: true
#    generate-ddl: true

